### ISSUE TITLE
Bug - Logging exception

### ISSUE THREAD

**Issue by MicroTrendsTom** [MicroTrendsLtd/NinjaTrader8#26]
An exception occurred writing trace output to log file 'D:\Users\Trader\Documents\NinjaTrader 8\\trace\ATS.NT8.20201208.Trace.txt'. System.IO.IOException: The process cannot access the file 'D:\Users\Trader\Documents\NinjaTrader 8\trace\ATS.NT8.20201208.Trace.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode)
   at System.Diagnostics.DefaultTraceListener.WriteToLogFile(String message, Boolean useWriteLine)

found in VS2019 debug session output

**Comment by MicroTrendsTom** [comment]
added  lock (logLockObject)  in  public static void WriteLine(string message)

**Comment by MicroTrendsTom** [comment]
seems to be fixed ok in that commit
